#!/bin/bash
#https://www.tutorialspoint.com/unix/shell_scripting.htm
if [ $# == 1 ]
then
git config --global user.email dhruvsavani510@gmail.com
git add .
#git commit -m "20200220_10_02"
git commit -m $1
git push origin master
fi
